{% set version = "0.1-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-miscf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/miscF_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/miscF/miscF_{{ version }}.tar.gz
  sha256: 6bcae702e104e120a4ee2ebbbc9cfc4578719aab7c2f0b1349d260dcbf98dc3c

build:
  number: 4
  # jags not available on win
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass >=7.3_45
    - r-mcmcpack >=1.2_4
    - r-r2jags >=0.5_7
    - r-mvtnorm >=0.9_9992
  run:
    - r-base
    - r-mass >=7.3_45
    - r-mcmcpack >=1.2_4
    - r-r2jags >=0.5_7
    - r-mvtnorm >=0.9_9992

test:
  commands:
    - $R -e "library('miscF')"           # [not win]
    - "\"%R%\" -e \"library('miscF')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=miscF
  license: GPL-2.0-or-later
  summary: Various functions for random number generation, density  estimation, classification, curve fitting, and spatial  data analysis.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: miscF
# Title: Miscellaneous Functions
# Version: 0.1-4
# Author: Dai Feng
# Description: Various functions for random number generation, density  estimation, classification, curve fitting, and spatial  data analysis.
# Maintainer: Dai Feng <dai_feng@merck.com>
# Depends: R (>= 3.0.2), MASS (>= 7.3-45), R2jags (>= 0.5-7)
# Imports: MCMCpack (>= 1.2-4), mvtnorm (>= 0.9-9992)
# Suggests: mixAK (>= 2.6), BRugs (>= 0.8-6)
# License: GPL
# NeedsCompilation: yes
# Packaged: 2018-02-16 21:41:16 UTC; dai
# Repository: CRAN
# Date/Publication: 2018-02-16 22:59:53 UTC
