travis:
  secure:
    BINSTAR_TOKEN: nUsxriV9G84ivJqNDtwv4itEmAP5ddsuqDWZFbzhOaiiZqRgFjhhtEGy0RJ0fv4ov80MALNceldFqklQdq0UoKR0nZGel67u0stHNS9cNqswNI4KAjkixUkZJG4qRGUHK2ZIke7hJQlCBfcfuKh+kYLWfGNOGMPjbp3xzK0cRRabLKCUIT2+dpWc1ih9QUbLuaFD3cSCJtpRtF7WsZb7C36QCIs9uN/chTaVkCApQGbFgkCaQH0R5y62+pnApNUb9IKYaJ893x1J9esw/yajpaUuKE3bu4SezMgR2xQMk0XaTtcDjLtFOSkovV68zy/u4tQB5GESHPPTN/4F37FWPBlovVOwg4xVZRMslrK08sRs4vvzjBnJY9BTNDlwm0OwHYxmdHcklX5Acmwf+VQMJrPQVi9bWYxLOsn5NNRku0OdNBD1cu0vSEyn1DNeu0YY9ZBeiymHNIft03G8jrNwcE3FyrV9zw188GVB4vYclz4s8PGtsJ1XSuTx2anA5jUtKxBh7jZr4qj1O/XHusCnM8ADHoiWqRYv7pUyOYST7m2v7uo+tHgTLfZsBzcFzIrvYKAXEI1o+JF0DrFUTYJ+rZkKN6VxD/fmPLi3zPtMWQ4G/opDTHNtFKNU0m5tROHudi6ChcKbjMVTYBFKYiNOVZ7DE9ODfGVeh+Hj1LdkaRw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
